SASS = node_modules/.bin/sass

target = ../../MacDown/Resources/Styles/GitHub-2020.css

all: $(target)

$(target): index.sass package-lock.json
	$(SASS) --no-source-map --load-path=node_modules $< $@.tmp
	sed 's/\.markdown-body/body/g' $@.tmp > $@
	$(RM) $@.tmp

clean:
	$(RM) $(target)

.PHONY: all clean
